introduction:
  data:
    slides:
      0:
        id: 0
        caption: Building 'static' HTML5 applications.
        content: |
          <p>using Thor & Middleman to manage multiple similar CoffeeScript & Backbone powered applications. 
          <p>@francpaul</p>
          <p>francois@rails.co.za</p>
      1:
        id: 1
        caption: Assumptions
        content: |
          <ul>
            <li>Familiar with web frameworks.</li>
            <li>Want to create html5 applications.</li>
            <li>These applications share a lot of structures.</li>
            <li>Javascript hurts your eyes.</li>
          </ul>
