introduction:
  settings:
    name: Introduction
    home_image: /images/server.jpg
  data:
    slides:
      0:
        id: 0
        caption: Thor & Middleman
        content: |
          <section class='middle'>
          <p class='color1'>building multiple similar CoffeeScript applications </p>
          <h2>@francpaul</h2>
          </section>
      1:
        id: 1
        caption: Assumptions
        content: |
          <section>
          <ul class='bulleted'>
            <li>Familiar with web frameworks.</li>
            <li>Want to create html5 applications.</li>
            <li>These applications share a lot of structures.</li>
            <li>Javascript hurts your eyes.</li>
          </ul>
          </section>
